### ISSUE TITLE
[Bug?] Configuration isnt created

### ISSUE THREAD

**Issue by fwenny** [Vl4dimyr/CaptainShotgunModes#8]
It says in the change log:
Configuration for default mode and enable/disable modes selection

But I see no configuration file created

**Comment by fwenny** [comment]
Found this in my LogOutput

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 0100001c (from typeref, class/assembly On.RoR2.UI.SkillIcon, MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.SkinDef:Awake()

**Comment by Vl4dimyr** [comment]
Thanks for reporting. What version of BepInEx and R2API do you have? I'll try to find out if I can fix this soon.

**Comment by fwenny** [comment]
BepInEx 5.3.1
R2API 2.5.14

**Comment by fwenny** [comment]
I thought it was just the config, but the whole mod doesnt seem to work. :c

**Comment by Vl4dimyr** [comment]
Ok what other mods are you using? Maybe there is a conflict or so?

**Comment by fwenny** [comment]
Heres the log file, it should contain all the errors and all the mods I have. Ive noticed some other mods throw a similar error (mostly Reins mods)

[LogOutput.log](https://github.com/Vl4dimyr/CaptainShotgunModes/files/5188013/LogOutput.log)

**Comment by fwenny** [comment]
Heres the log file, it should contain the error the mod is throwing and all the mods that i use

[LogOutput.log](https://github.com/Vl4dimyr/CaptainShotgunModes/files/5188998/LogOutput.log)

**Comment by Vl4dimyr** [comment]
I've just tried to install all the mods you are using with the same versions you are using. I did not find `EngiShieldNotification` and `FluffyLabsConfigManagerTools` but aside from this I did start the game selected captain and started the run, I then tested my mod's features and everything was working fine. So I cannot reproduce your issue. Please let me know if you still have this issue! And if possible please describe every step that leads to the issue.

**Comment by fwenny** [comment]
I mean, Im not sure what to tell you about the reproduction steps. I just launch the game and see this in my log:

```
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 0100001c (from typeref, class/assembly On.RoR2.UI.SkillIcon, MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.SkinDef:Awake()
```

I then enter a match and try pressing 1 2 or 3 or use the mousewheel and nothing happens.

If theres any other info I can provide, please let me know.

**Comment by Vl4dimyr** [comment]
I will try to add some fallbacks to prevent this, but since I don't get this error I cannot test it.

**Comment by megAJuan** [comment]
I'm also having issued with this mod, though it's only with some modpacks. Nevertheless, I get this error and I have no idea how to fix it.
![2020-09-14](https://user-images.githubusercontent.com/71277700/93106180-9636c600-f675-11ea-8305-78fbb6b787e3.png)

the r2modman pack code is: m1ZsIa5CGz

**Comment by Vl4dimyr** [comment]
@megAJuan this seems to be a bug with LighterPatcher I created an issue: https://github.com/harbingerofme/LighterPatcher/issues/2

**Comment by megAJuan** [comment]
I tried disabling it and running the pack again, this time I
![2020-09-14 (4)](https://user-images.githubusercontent.com/71277700/93111161-dc8f2380-f67b-11ea-9019-41fbecb19674.png)
 was met with this

**Comment by Vl4dimyr** [comment]
Ok this looks like some other mod does something with the skill icons, please find out which one is causing this.

**Comment by megAJuan** [comment]
i cant figure out what mod is causing this error. I can sent you the mods via code on r2modman if that helps, but for the life of me I cannot figure out why this is happening

r2modman code: wKyuIJw7Va

**Comment by IstAviX** [comment]
I'm also having this issue, so I did some tests to see what the problem is. Tried disabling all of my mods except this one on my r2modman profile, and still had BepInEx throwing a TypeLoadException (same as the screenshot from megAJuan). I created a brand new profile, with only CaptainShotgunModes, the mod worked fine. Added a few other mods, still fine. Then I tried to create a profile with only this mod, and LighterPatcher, and the mod broke. Even after deleting LighterPatcher, the mod was still broken. So I'm pretty sure it's LighterPatcher that's messing up the mod. 

Oh, and forgot to precise that it used to work perfectly fine when the mod was still in 1.0.0

**Comment by Vl4dimyr** [comment]
LighterPatcher was fixed 🙂 Please let me know if there are still issues left.

**Comment by megAJuan** [comment]
yeah uh... im still getting the same issues as before. like, line by line code by code the exact same issues

**Comment by fwenny** [comment]
> 
> 
> LighterPatcher was fixed slightly_smiling_face Please let me know if there are still issues left.

I do not see a LightPatcher update nor your mod update.

**Comment by fwenny** [comment]
LightPatcher update was released, mod works great now. =)
